[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "revoletion"
version = "1.7.1"
description = "Resilient Electric Vehicle Optimization model for Local Energy TransitION"
authors = [
    { name = "Philipp Rosner", email = "philipp.rosner@tum.de" },
    { name = "Brian Dietermann", email = "brian.dietermann@tum.de"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopy",
    "gurobipy",
    "highspy",
    "holidays",
    "numpy",
    "numpy_financial",
    "oemof.solph==0.6.3",
    "pandas>=3.0",
    "plotly",
    "psutil",
    "pvlib>=0.13.0",
    "rainflow",
    "scipy",
    "scikit-learn",
    "simpy",
    "timezonefinder",
    "tk",
    "windpowerlib",
    "pydantic",
    "revoletion-core>=1.0.0.dev0",
    "pypsa>=1.2.0",
    "polars[rtcompat]",
    "prefect>=3.7.4",
    "httpx>=0.28",
    "aiofiles",
    "aiocsv",
    "tqdm"
]

[dependency-groups]
tests = [
    "coverage[toml]>=7.10.7",
    "pytest>=8.4.2",
]

dev = [
    "ipykernel",
    "jupyterlab",
    "pre-commit",
    "pymupdf",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
revoletion = ["data/*"]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
# Enable import sorting.
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
# Ignore unused imports in __init__.py files.
"__init__.py" = ["E402", "F401"]

[project.scripts]
revoletion = "revoletion.__main__:main"

[tool.pytest.ini_options]
# Disable warnings spam
addopts = "-p no:warnings"
testpaths = ["tests"]

[tool.coverage.run]
source = ["revoletion"]

[[tool.uv.index]]
name = "internal"
url = "https://gitlab.lrz.de/api/v4/projects/260872/packages/pypi/simple"
explicit = true

[tool.uv.sources]
revoletion-core = { index = "internal" }
