# GitHub Action Workflow to build REVOL-E-TION docker image (with example data only)

name: Build REVOL-E-TION Docker Image

on:
  push:
    branches: [main]

jobs:
  build_image_to_registry:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/tumftm/revol-e-tion/docker-image:latest
          labels: |
            git-commit=https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          build-args: |
            COMMIT=https://github.com/${{ github.repository }}/commit/${{ github.sha }}